on:
  # pull_request:
  #   branches:
  #     - main
  #     - master
  push:
    branches:
      - final
      #- master

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

        env:
          KEY_JKS: ${{ secrets.KEYSTORE2 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE: ${{ secrets.KEY_STORE }}
          run: echo $KEY_JKS > key.jks && flutter pub get && flutter test && flutter build apk --release

      # - run: flutter pub get

      # - run: flutter test

      # - run: flutter build apk --debug --split-per-abi

      # - run: flutter build appbundle

      # - run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
